# Generated by Django 5.1.1 on 2024-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
