# Generated by Django 5.1.1 on 2024-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_address_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
