# Generated by Django 5.1.1 on 2024-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
