# Generated by Django 5.1.1 on 2024-09-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_payment_product_payment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
    ]
